repository:
  name: saas-boilerplate
  description: Next.js 14 SAAS Boilerplate with Supabase
  homepage: https://your-domain.com
  topics: nextjs, typescript, supabase, saas
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true

labels:
  - name: bug
    color: d73a4a
  - name: enhancement
    color: a2eeef
  - name: documentation
    color: 0075ca
  - name: dependencies
    color: 0366d6

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: ["test", "lint", "type-check"]
      enforce_admins: false
      restrictions: null
